### PR TITLE
Provide useful error for "Cannot find trait Hash in this scope"

### LINKED ISSUE #5129: Provide temporary fix for the "Cannot find trait Hash in this scope" issue
_(Adapted from our discussion)_

When calling one of the hash functions (such as `sha256`) on a type, error is thrown with span inside the standard library saying that the `Hash` trait is out of scope.

image

What the error really means is that the impl for that particular type is not in scope at the call site. To fix the issue one needs to `use std::hash::Hash`.

The underlying issue in Sway is that we don't have a compile step to collect all the impls for a trait, so when you use one it has to be manually imported. And the only way to import impls is by importing the trait they relate to if and only if the impls are in the same module as the trait definition.

Considering how often the issue appears and how confusing the error message is, we want to provide a temporary solution before implementing collecting impls for a trait.

Potential temporary fixes: 
1. Putting `Hash` (and hence the impls) in the prelude. Cons: Bloating the default namespace is bad practice in general. Removing things from prelude later on is a breaking change. Programmers still need to `use std::hash::*`.
1. Provide helpful error message that will point to the solution. We have to see how much effort would it be to come up with a good heuristic and how helpful the message will really be.

### PR DESCRIPTION
**Pull request by ironcev**
## Description

This PR closes #5129 by providing a detailed guidelines to programmers on how to fix the "Cannot find trait XYZ in this scope". The issue is very prominent in the case of the `Hash` trait as demonstrated in the #5084.

We need to guide programmers at the moment because fixing the root cause will take some time.

The PR:
- replaces the current two misleading and redundant error messages with a clear instruction how to fix the issue at the call site.
- provides the guidelines in a general case, and not only for the prominent issue with the `Hash` trait.
- removes the redundant `SymbolNotFound` error in favor of more specific `TraitNotFound`

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by sdankel — APPROVED** [review]
LGTM 🚀
